language : node_js
node_js :
 - 17
install:
 - npm install
script:
 - npm test
 # Send coverage data to Coveralls
after_success:
 - npm run coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"